name: Docblock MacOS

on:
    pull_request: null

jobs:
    docblock_macos:
        strategy:
            fail-fast: false
            matrix:
                platform: [ubuntu-latest, macos-latest]

        runs-on: ${{ matrix.platform }

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    coverage: none
                    tools: composer:v2

            -   run: composer install --no-progress --ansi

            -   run: bin/rector p abz/SomeFile.php -n -a abz/SomeFile.php
